package aravia

type HttpMethod string
type HttpStatus int

var (
	MethodGet     = HttpMethod("GET")
	MethodHead    = HttpMethod("HEAD")
	MethodPost    = HttpMethod("POST")
	MethodPut     = HttpMethod("PUT")
	MethodPatch   = HttpMethod("PATCH")
	MethodDelete  = HttpMethod("DELETE")
	MethodConnect = HttpMethod("CONNECT")
	MethodOptions = HttpMethod("OPTIONS")
	MethodTrace   = HttpMethod("TRACE")
)

var (
	StatusContinue           = HttpStatus(100)
	StatusSwitchingProtocols = HttpStatus(101)
	StatusProcessing         = HttpStatus(102)
	StatusEarlyHints         = HttpStatus(103)

	StatusOK                   = HttpStatus(200)
	StatusCreated              = HttpStatus(201)
	StatusAccepted             = HttpStatus(202)
	StatusNonAuthoritativeInfo = HttpStatus(203)
	StatusNoContent            = HttpStatus(204)
	StatusResetContent         = HttpStatus(205)
	StatusPartialContent       = HttpStatus(206)
	StatusMultiStatus          = HttpStatus(207)
	StatusAlreadyReported      = HttpStatus(208)
	StatusIMUsed               = HttpStatus(226)

	StatusMultipleChoices   = HttpStatus(300)
	StatusMovedPermanently  = HttpStatus(301)
	StatusFound             = HttpStatus(302)
	StatusSeeOther          = HttpStatus(303)
	StatusNotModified       = HttpStatus(304)
	StatusUseProxy          = HttpStatus(305)
	_                       = HttpStatus(306)
	StatusTemporaryRedirect = HttpStatus(307)
	StatusPermanentRedirect = HttpStatus(308)

	StatusBadRequest                   = HttpStatus(400)
	StatusUnauthorized                 = HttpStatus(401)
	StatusPaymentRequired              = HttpStatus(402)
	StatusForbidden                    = HttpStatus(403)
	StatusNotFound                     = HttpStatus(404)
	StatusMethodNotAllowed             = HttpStatus(405)
	StatusNotAcceptable                = HttpStatus(406)
	StatusProxyAuthRequired            = HttpStatus(407)
	StatusRequestTimeout               = HttpStatus(408)
	StatusConflict                     = HttpStatus(409)
	StatusGone                         = HttpStatus(410)
	StatusLengthRequired               = HttpStatus(411)
	StatusPreconditionFailed           = HttpStatus(412)
	StatusRequestEntityTooLarge        = HttpStatus(413)
	StatusRequestURITooLong            = HttpStatus(414)
	StatusUnsupportedMediaType         = HttpStatus(415)
	StatusRequestedRangeNotSatisfiable = HttpStatus(416)
	StatusExpectationFailed            = HttpStatus(417)
	StatusTeapot                       = HttpStatus(418)
	StatusMisdirectedRequest           = HttpStatus(421)
	StatusUnprocessableEntity          = HttpStatus(422)
	StatusLocked                       = HttpStatus(423)
	StatusFailedDependency             = HttpStatus(424)
	StatusTooEarly                     = HttpStatus(425)
	StatusUpgradeRequired              = HttpStatus(426)
	StatusPreconditionRequired         = HttpStatus(428)
	StatusTooManyRequests              = HttpStatus(429)
	StatusRequestHeaderFieldsTooLarge  = HttpStatus(431)
	StatusUnavailableForLegalReasons   = HttpStatus(451)

	StatusInternalServerError           = HttpStatus(500)
	StatusNotImplemented                = HttpStatus(501)
	StatusBadGateway                    = HttpStatus(502)
	StatusServiceUnavailable            = HttpStatus(503)
	StatusGatewayTimeout                = HttpStatus(504)
	StatusHTTPVersionNotSupported       = HttpStatus(505)
	StatusVariantAlsoNegotiates         = HttpStatus(506)
	StatusInsufficientStorage           = HttpStatus(507)
	StatusLoopDetected                  = HttpStatus(508)
	StatusNotExtended                   = HttpStatus(510)
	StatusNetworkAuthenticationRequired = HttpStatus(511)
)
